version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: doenerOrder
      POSTGRES_PASSWORD: doenerOrder
    volumes:
      - doenerOrder-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  doenerOrder-db: {}